### ISSUE TITLE
有些疑问要请教下？

### ISSUE THREAD

**Issue by ShenJieSuzhou** [YouXianMing/YoCelsius#11]
请问下，你这些动画都是原生代码开发的吗，因为我看爱彼迎有个开源的动画库，通过用Adobe的AE工具制作的动画，该库可以调用。

**Comment by Czhiheng** [comment]
？？发错了吧

**Comment by ShenJieSuzhou** [comment]
@Czhiheng 没有，我就是看这个app,里面有很多动画效果，是不是都是用OC直接写出来的。

**Comment by YouXianMing** [comment]
都是用OC写出来的.
