### ISSUE TITLE
请问一下，天气图标是怎么根据 self.glowLabel.text 的值进行显示的？

### ISSUE THREAD

**Issue by xukunluren** [YouXianMing/YoCelsius#8]
在WeatherIconView 里面设置了  glowLabel，经过数据的处理返回字母，如：self.glowLabel.text = @“D”时，为什么显示的是阴天的图标？工程里哪里进行的设置？谢谢。

**Comment by YouXianMing** [comment]
字体里面的值对应着图标 ^_^
